# Generated by Django 4.2.6 on 2023-10-11 04:43

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Details",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("dob", models.DateField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=10)),
                (
                    "phone",
                    phone_field.models.PhoneField(
                        blank=True, help_text="Contact phone number", max_length=31
                    ),
                ),
                ("mail", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=250)),
                ("dep", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("purpose", models.CharField(max_length=100)),
                ("pen", models.BooleanField()),
                ("paper", models.BooleanField()),
            ],
        ),
    ]
