# Generated by Django 4.2.6 on 2023-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolStore", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="paper",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="details", name="pen", field=models.BooleanField(default=False),
        ),
    ]
