# Generated by Django 4.2.6 on 2023-10-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schoolStore", "0005_alter_details_paper_alter_details_pen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details", name="phone", field=models.CharField(max_length=250),
        ),
    ]
